apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: quote-svc
  namespace: stage
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~8.0
spec:
  releaseName: quote-svc-stage
  chart:
    git: ssh://git@github.com/bashofmann/flux-state
    ref: master
    path: charts/quote-svc
  values:
    image:
      repository: bashofmann/k8s-workshop-quote-svc
      tag: 8.0.0
    replicaCount: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
